salary_train <- read.csv(file.choose())
salary_test <- read.csv(file.choose())
attach(salary_train)
attach(salary_test)
library(kernlab)
best <- function(kern) {
  salary_classifier3 <- ksvm(Salary~.,data=salary_train,kernel=kern)
  predict.poly <- predict(salary_classifier3,salary_test)
  table(predict.poly,salary_test$Salary)
  d <- predict.poly==salary_test$Salary
  return(d)
}
res1 <- best(kern = "rbfdot")
prop.table(table(res1))
res2 <- best(kern = "tanhdot")
prop.table(table(res2))
res3 <- best(kern = "laplacedot")
prop.table(table(res3))
res4 <- best(kern="besseldot")
prop.table(table(res4))
res5 <- best(kern="anovadot")
prop.table(table(res5))
res6 <- best(kern = "splinedot")
prop.table(table(res6))
res7 <- best(kern = "vanilladot")
prop.table(table(res7))
res8 <- best(kern="polydot")
prop.table(table(d))
#we can found the best kernal for classification osing SVM